import { Container, Header } from '@/src/shared/components'
import { Suspense } from 'react'

export const metadata = {
	title: 'Next Pizza | Корзина',
	description: 'Generated by Next.js',
}

export default function CheckoutLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<main className='min-h-screen bg-[#f4f1ee]'>
			<Container>
				<Suspense>
					<Header hasCart={false} hasSearch={false} />
				</Suspense>
				{children}
			</Container>
		</main>
	)
}
